/** Commercial destinations for editorial articles. Guides keep their own
 * comparison/informational intent and send service enquiries to the owner. */
const services = {
  chef: { href: '/private-chef-dubai', label: 'private chef services', anchor: 'myCHEF private chef services in Dubai' },
  chefPricing: { href: '/private-chef-dubai/pricing', label: 'private chef pricing', anchor: 'private chef prices and booking options' },
  catering: { href: '/catering-dubai', label: 'catering', anchor: 'myCHEF catering services in Dubai' },
  corporate: { href: '/corporate', label: 'corporate catering', anchor: 'corporate catering in Dubai' },
  corporateEvent: { href: '/corporate-event-catering-dubai', label: 'corporate event catering', anchor: 'corporate event catering in Dubai' },
  office: { href: '/office-catering-dubai', label: 'office catering', anchor: 'office catering in Dubai' },
  breakfast: { href: '/breakfast-catering-dubai', label: 'breakfast catering', anchor: 'breakfast catering in Dubai' },
  yacht: { href: '/yachts', label: 'yacht catering', anchor: 'yacht catering in Dubai' },
  birthday: { href: '/birthday-catering-dubai', label: 'birthday catering', anchor: 'birthday catering in Dubai' },
  wedding: { href: '/wedding-catering-dubai', label: 'wedding catering', anchor: 'wedding catering in Dubai' },
  dropOff: { href: '/drop-off-catering-dubai', label: 'drop-off catering', anchor: 'drop-off catering in Dubai' },
  mealPrep: { href: '/weekly-meal-prep-dubai', label: 'weekly meal preparation', anchor: 'weekly meal preparation with a chef in Dubai' },
  villa: { href: '/villas-private-residences', label: 'villa dining', anchor: 'private chef dining for Dubai villas' },
  dining: { href: '/luxury-dining-experiences', label: 'private dining', anchor: 'private dining experiences in Dubai' },
  class: { href: '/private-cooking-classes-dubai', label: 'private cooking classes', anchor: 'private cooking classes in Dubai' },
  party: { href: '/private-party-catering-dubai', label: 'private party catering', anchor: 'private party catering in Dubai' },
  bbq: { href: '/bbq-catering-dubai', label: 'BBQ catering', anchor: 'BBQ catering in Dubai' },
  arabic: { href: '/arabic-catering-dubai', label: 'Arabic catering', anchor: 'Arabic catering in Dubai' },
  brunch: { href: '/brunch-catering-dubai', label: 'brunch catering', anchor: 'brunch catering in Dubai' },
  cocktail: { href: '/cocktail-party-catering-dubai', label: 'cocktail party catering', anchor: 'cocktail party catering in Dubai' },
  desert: { href: '/desert-dining-dubai', label: 'desert dining', anchor: 'desert dining in Dubai' },
  glutenFree: { href: '/allergy-safe-catering-dubai', label: 'allergy-aware catering', anchor: 'allergy-aware catering and dietary planning in Dubai' },
  grazing: { href: '/grazing-table-dubai', label: 'grazing tables', anchor: 'grazing tables in Dubai' },
  halal: { href: '/halal-catering-dubai', label: 'halal catering', anchor: 'halal catering in Dubai' },
  iftar: { href: '/iftar-catering-dubai', label: 'iftar catering', anchor: 'iftar catering in Dubai' },
  vegan: { href: '/vegan-catering-dubai', label: 'vegan catering', anchor: 'vegan catering in Dubai' },
  buffet: { href: '/buffet-catering-dubai', label: 'buffet catering', anchor: 'buffet catering in Dubai' },
  canape: { href: '/canape-catering-dubai', label: 'canapé catering', anchor: 'canapé catering in Dubai' },
  christmas: { href: '/christmas-catering-dubai', label: 'Christmas catering', anchor: 'Christmas catering in Dubai' },
  diwali: { href: '/diwali-catering-dubai', label: 'Diwali catering', anchor: 'Diwali catering in Dubai' },
  production: { href: '/production-catering-dubai', label: 'production catering', anchor: 'production catering in Dubai' },
} as const

export const BLOG_SERVICE_TARGETS: Record<string, keyof typeof services> = {
  'catering-for-embassies-in-dubai-complete-guide': 'corporateEvent',
  'private-chefs-for-new-parents-in-dubai-complete-guide': 'chef',
  'catering-for-film-and-tv-productions-in-dubai-complete-guide': 'production',
  'private-chefs-for-expat-families-in-dubai-complete-guide': 'chef',
  'catering-for-real-estate-open-houses-in-dubai-complete-guide': 'corporateEvent',
  'mychef-vs-dish-ae-which-is-better-in': 'catering',
  'best-home-catering-services-in-dubai': 'catering',
  'mychef-vs-monchef-which-is-better-in': 'catering',
  'mychef-vs-taste-studio-which-is-better-in': 'catering',
  'best-arabic-catering-companies-in-dubai': 'arabic',
  'best-bbq-catering-companies-in-dubai': 'bbq',
  'best-brunch-catering-services-in-dubai': 'brunch',
  'best-catering-companies-in-dubai': 'catering',
  'best-cocktail-party-catering-companies-in-dubai': 'cocktail',
  'best-corporate-event-catering-companies-in-dubai': 'corporateEvent',
  'best-corporate-lunch-catering-companies-in-dubai': 'office',
  'best-cozymeal-alternatives-for-private-dining-in-dubai': 'dining',
  'best-desert-dining-catering-companies-in-dubai': 'desert',
  'best-drop-off-catering-services-in-dubai': 'dropOff',
  'best-gluten-free-catering-companies-in-dubai': 'glutenFree',
  'best-grazing-table-catering-companies-in-dubai': 'grazing',
  'best-halal-catering-companies-in-dubai': 'halal',
  'best-kids-birthday-party-caterers-in-dubai': 'birthday',
  'best-luxury-private-dining-experiences-in-dubai': 'dining',
  'best-meal-prep-services-in-dubai': 'mealPrep',
  'best-private-chefs-for-villas-in-dubai': 'villa',
  'best-private-chefs-in-dubai-for-home-dining': 'chef',
  'best-private-cooking-class-experiences-in-dubai': 'class',
  'best-ramadan-iftar-catering-companies-in-dubai': 'iftar',
  'best-vegan-catering-services-in-dubai': 'vegan',
  'best-wedding-catering-companies-in-dubai': 'wedding',
  'best-yacht-catering-services-in-dubai': 'yacht',
  'buffet-layout-planning-dubai': 'buffet',
  'canape-reception-planning-dubai': 'canape',
  'cateringdubai-ae-alternatives-in': 'catering',
  'cateringindubai-alternatives-in': 'catering',
  'cedar-tree-catering-alternatives-in': 'catering',
  'chef-maison-alternatives-in': 'chef',
  'christmas-lunch-at-home-planning-dubai': 'christmas',
  'compare-catering-quotes-dubai': 'catering',
  'dinner-party-timeline-dubai': 'party',
  'dish-ae-alternatives-in': 'catering',
  'diwali-party-at-home-planning-dubai': 'diwali',
  'household-menu-brief-dubai': 'chef',
  'how-much-does-a-private-chef-cost-in-dubai-in': 'chefPricing',
  'kids-and-adults-party-menu-dubai': 'birthday',
  'mixed-diet-dinner-party-dubai': 'party',
  'monchef-alternatives-in': 'chef',
  'mychef-vs-cateringindubai-which-is-better-in': 'catering',
  'mychef-vs-chef-maison-which-is-better-in': 'chef',
  'mychef-vs-pinch-gourmet-which-is-better-in': 'catering',
  'office-breakfast-planning-dubai': 'breakfast',
  'outdoor-villa-catering-kitchen-dubai': 'party',
  'pinch-gourmet-alternatives-in': 'catering',
  'private-chef-kitchen-preparation-dubai': 'chef',
  'private-chef-trial-dubai': 'chef',
  'smart-catering-alternatives-in': 'catering',
  'take-a-chef-alternatives-in': 'chef',
  'taste-studio-alternatives-in': 'catering',
  'three-hour-yacht-party-food-timeline-dubai': 'yacht',
  'wedding-menu-tasting-dubai': 'wedding',
}

export function blogServiceFor(slug: string) {
  const key = BLOG_SERVICE_TARGETS[slug]
    ?? (/private-chef|household|chef-maison|take-a-chef/.test(slug) ? 'chef'
      : /yacht/.test(slug) ? 'yacht'
        : /corporate|office/.test(slug) ? 'corporate' : 'catering')
  return services[key]
}
