import settings from './privateDiningSettings.json'
export const DINING_CONFIG = settings
export const DINING_ESTIMATE_NOTE = 'This is an estimate and a booking request. Your coordinator confirms availability, dietary requirements, the menu and final price in writing.'
export const DINING_FAQS = [
  { q: 'What does the food and chef estimate include?', a: 'Ingredients and preparation are included. Delivery brings ready-to-serve food with no on-site staff. Cooking in your kitchen includes cooking, plating, food service and kitchen clean-up. Buffet service includes food preparation, a chef and the required assistants. The estimate shows area transport, selected drinks and 5% VAT separately. Furniture, tableware, buffet equipment, decorations and cakes are quoted separately when requested.' },
  { q: 'What are the minimum guest numbers and booking notice?', a: 'Cooking in your kitchen starts at six guests, delivered food at ten and buffet service at twenty. Book at least five calendar days ahead in Dubai time. Cooking at home requires confirmation that a fully equipped kitchen is available.' },
  { q: 'Can I choose vegetarian and vegan alternatives?', a: 'Yes. Choose one cuisine and three to eleven dishes, then select replacement dishes for vegetarian, vegan or other dietary groups. Each guest belongs to one group and is charged for one menu. Tell us about allergies so the chef can confirm whether your requirements can be accommodated.' },
  { q: 'Do I need to choose a chef?', a: 'No. We include the appropriate chef automatically. On-site bookings add one assistant from nine guests, two from twenty and one more at each ten-guest step. Buffet estimates cap assistants at five. Final staffing and specialist dishes are confirmed before booking.' },
  { q: 'Does WhatsApp confirm my booking?', a: 'No. It opens a prefilled request containing your service, menus, date, guests, dietary groups, area, estimate and extras. Send it to our team to confirm availability and booking terms. Cakes, furniture and decoration are separate quote requests.' },
]
