/** Visual direction for the active Private Chef journey. Identity/portfolio assets stay authentic. */
export const CHEF_IMAGE_ROOT = '/images/private-chef-2026/'
export const chefImages = {
  household: { alt: 'Chef finishing a roast chicken platter in a light-filled home kitchen', position: '56% 50%' },
  planning: { alt: 'Chef and homeowner discussing a weekly menu at the kitchen table', position: '50% 48%' },
  'meal-prep': { alt: 'Freshly cooked meals portioned into glass containers in a home kitchen', position: '50% 60%' },
  'family-table': { alt: 'Chicken, vegetables and fresh salad ready for a relaxed family lunch', position: '50% 60%' },
  wellness: { alt: 'Salmon, lentils and colourful vegetables served in a ceramic bowl', position: '50% 50%' },
  craft: { alt: 'Chef carefully finishing a fish dish with sauce and seasonal vegetables', position: '40% 50%' },
  'clean-kitchen': { alt: 'An orderly home kitchen with clean crockery and a folded linen cloth', position: '55% 50%' },
  'team-service': { alt: 'Culinary and service team preparing a villa dinner', position: '50% 50%' },
  'villa-evening': { alt: 'An intimate dinner table on a villa terrace at dusk', position: '50% 55%' },
  apartment: { alt: 'Chef preparing dinner in a compact contemporary apartment kitchen', position: '50% 50%' },
  'chefs-table': { alt: 'A chef finishing tasting plates as guests watch from the dining table', position: '50% 50%' },
  pasta: { alt: 'Fresh ravioli being folded by hand on a wooden kitchen board', position: '50% 60%' },
  arabic: { alt: 'A Middle Eastern sharing table with mezze, chicken skewers and flatbread', position: '50% 50%' },
  dessert: { alt: 'Vanilla and pistachio mille-feuille with berries on an ivory plate', position: '50% 55%' },
  'cooking-class': { alt: 'Chef guiding a guest through fresh pasta preparation at home', position: '50% 50%' },
  romantic: { alt: 'An intimate candlelit dinner for two with thoughtful table details', position: '50% 58%' },
  desert: { alt: 'A beautifully set dinner table beside desert dunes at sunset', position: '50% 58%' },
  breakfast: { alt: 'Fresh breakfast dishes being served in a bright family kitchen', position: '50% 55%' },
  ingredients: { alt: 'Fresh seasonal vegetables, herbs and pantry ingredients on a kitchen island', position: '50% 50%' },
  birthday: { alt: 'An elegant birthday dinner table with a small cake and fresh flowers', position: '50% 55%' },
} as const
export type ChefImageKey = keyof typeof chefImages
export const chefImage = (key: ChefImageKey, width = 1200) => `${CHEF_IMAGE_ROOT}${key}-${width}.webp`
export const chefImageSrcSet = (key: ChefImageKey) => [480, 800, 1200, 1536].map(w => `${chefImage(key, w)} ${w}w`).join(', ')

export const chefPageImages: Record<string, ChefImageKey> = {
  '/private-chef-dubai': 'household',
  '/private-chef-dubai/how-it-works': 'planning',
  '/private-chef-dubai/our-chefs': 'team-service',
  '/private-chef-dubai/quality-training': 'craft',
  '/private-chef-dubai/privacy-security': 'clean-kitchen',
  '/private-chef-dubai/pricing': 'ingredients',
  '/private-chef-dubai/how-your-plan-works': 'family-table',
  '/full-time-private-chef-dubai': 'breakfast',
  '/part-time-private-chef-dubai': 'household',
  '/weekly-meal-prep-dubai': 'meal-prep',
  '/wellness-meal-prep-dubai': 'wellness',
  '/our-chefs': 'team-service',
  '/how-we-vet-our-chefs': 'craft',
  '/villas-private-residences': 'villa-evening',
  '/apartment-private-dining-dubai': 'apartment',
  '/chefs-table-dubai': 'chefs-table',
  '/halal-private-dining-dubai': 'arabic',
  '/luxury-dining-experiences': 'chefs-table',
  '/private-cooking-classes-dubai': 'cooking-class',
  '/romantic-dinner-dubai': 'romantic',
  '/proposal-dinner-dubai': 'romantic',
  '/desert-dining-dubai': 'desert',
  '/guide/private-dining-dubai': 'villa-evening',
  '/private-chef-vs-catering-dubai': 'family-table',
  '/blog/how-much-does-private-chef-cost-dubai': 'ingredients',
  '/blog/how-to-hire-a-private-chef-dubai': 'planning',
  '/blog/best-private-chef-birthday-dinner-dubai': 'birthday',
  '/blog/private-chef-palm-jumeirah-guide': 'villa-evening',
  '/blog/best-private-cooking-class-experiences-in-dubai': 'cooking-class',
  '/blog/best-luxury-private-dining-experiences-in-dubai': 'chefs-table',
  '/blog/best-private-chefs-for-villas-in-dubai': 'household',
  '/chefs/ahmed-executive-chef': 'craft',
  '/chefs/marco-italian-chef': 'pasta',
  '/chefs/layla-middle-eastern-chef': 'arabic',
  '/chefs/matteo-pastry-chef': 'dessert',
  '/how-it-works': 'planning',
  '/gallery': 'villa-evening',
  '/case-studies': 'villa-evening',
  '/quality-guarantee-dubai': 'craft',
}
// About owns its own editorial images, while sharing the light page shell.
export const isChefDesignPage = (path: string) => path === '/about' || Object.hasOwn(chefPageImages, path)
/** Explicit mapping only: unrelated service images do not change by accident. */
export const legacyChefImages: Record<string, ChefImageKey> = {
  "/images/blog/best-private-chef-birthday-dinner-dubai-2.webp": "birthday",
  "/images/blog/best-private-chef-birthday-dinner-dubai-hero.webp": "birthday",
  "/images/blog/how-much-does-private-chef-cost-dubai-2.webp": "ingredients",
  "/images/blog/how-much-does-private-chef-cost-dubai-3.webp": "ingredients",
  "/images/blog/how-much-does-private-chef-cost-dubai-hero.webp": "ingredients",
  "/images/blog/private-chef-palm-jumeirah-guide-2.webp": "villa-evening",
  "/images/blog/private-chef-palm-jumeirah-guide-3.webp": "villa-evening",
  "/images/blog/private-chef-palm-jumeirah-guide-hero.webp": "villa-evening",
  "/images/blog/how-to-hire-a-private-chef-dubai-hero.webp": "planning",
  "/images/blog/how-to-hire-a-private-chef-dubai-2.webp": "planning",
  "/images/blog/how-to-hire-a-private-chef-dubai-3.webp": "ingredients",
  "/images/blog/how-to-hire-a-private-chef-dubai-4.webp": "team-service",
  "/images/blog/how-to-hire-a-private-chef-dubai-5.webp": "craft",

  '/service-private-chef.webp': 'household',
  '/service-villa.webp': 'villa-evening',
  '/images/private-chef-dubai-hero.webp': 'household',
  '/images/private-chef-dubai-system.webp': 'meal-prep',
  '/images/private-chef-dubai-evening.webp': 'family-table',
  '/images/private-chef-dubai-household.webp': 'family-table',
  '/images/private-chef-dubai-chefs.webp': 'team-service',
  '/images/private-chef-dubai-daily-life.webp': 'breakfast',
  '/images/private-chef-dubai-who-for.webp': 'family-table',
  '/images/private-chef-dubai-why-independent.webp': 'craft',
  '/images/private-chef-dubai-how-it-works.webp': 'planning',
  '/images/private-chef-how-it-works-hero.webp': 'planning',
  '/images/private-chef-our-chefs-hero.webp': 'team-service',
  '/images/private-chef-quality-training-hero.webp': 'craft',
  '/images/private-chef-privacy-security-hero.webp': 'clean-kitchen',
  '/images/private-chef-pricing-hero.webp': 'ingredients',
  '/images/private-chef-dubai-who-does-what.webp': 'planning',
  '/images/private-chef-dubai-mix.webp': 'arabic',
  '/images/private-chef-dubai-chef-level.webp': 'craft',
  '/images/private-chef-dubai-where.webp': 'apartment',
  '/images/private-chef-dubai-cta.webp': 'clean-kitchen',
  '/images/private-chef-dubai-journey-brief.webp': 'planning',
  '/images/private-chef-dubai-journey-match.webp': 'team-service',
  '/images/private-chef-dubai-journey-profile.webp': 'ingredients',
  '/images/private-chef-dubai-journey-review.webp': 'planning',
  '/images/private-chef-dubai-manager.webp': 'planning',
  '/images/private-chef-dubai-rotation.webp': 'team-service',
  '/images/private-chef-dubai-year-later.webp': 'family-table',
  '/images/private-chef-dubai-life-breakfast.webp': 'breakfast',
  '/images/private-chef-dubai-life-children.webp': 'family-table',
  '/images/private-chef-dubai-life-guests.webp': 'villa-evening',
  '/images/weekly-meal-prep-dubai-hero.webp': 'meal-prep',
  '/images/healthy-catering-dubai-hero.webp': 'wellness',
  '/images/villa-catering-dubai-hero.webp': 'villa-evening',
  '/images/luxury-dining-dubai-hero.webp': 'chefs-table',
  '/images/romantic-dinner-dubai-hero.webp': 'romantic',
  '/images/proposal-dinner-dubai-hero.webp': 'romantic',
  '/images/desert-dining-dubai-hero.webp': 'desert',
  '/images/private-cooking-classes-dubai-hero.webp': 'cooking-class',
  '/images/chefs-table-dubai-hero.webp': 'chefs-table',
  '/images/halal-private-dining-dubai-hero.webp': 'arabic',
  '/images/about-mychef-dubai-hero.webp': 'team-service',
  '/images/mychef-dubai-about-team-hero.webp': 'team-service',
  '/images/how-we-vet-our-chefs-dubai-hero.webp': 'craft',
  '/menu-dessert.webp': 'dessert',
  '/menu-seafood.webp': 'wellness',
  '/menu-meat.webp': 'family-table',
}
export function chefImageKey(src?: string): ChefImageKey | undefined {
  if (!src) return undefined
  if (legacyChefImages[src]) return legacyChefImages[src]
  const key = src.split('/').pop()?.replace(/-(480|800|1200|1536)\.webp$/, '')
  return src.startsWith(CHEF_IMAGE_ROOT) && key && key in chefImages ? key as ChefImageKey : undefined
}
