// Generated by scripts/ryze-convert.mjs. Do not edit by hand.
export const RYZE_BLOG_PATHS: string[] = [
  "/blog/best-meal-prep-services-in-dubai",
  "/blog/best-private-chefs-in-dubai-for-home-dining",
  "/blog/best-catering-companies-in-dubai",
  "/blog/how-much-does-a-private-chef-cost-in-dubai-in"
]
