// Generated by scripts/ryze-convert.mjs. Do not edit by hand.
export const RYZE_BLOG_POSTS = [
  {
    "slug": "/blog/best-meal-prep-services-in-dubai",
    "title": "Best Meal Prep Dubai 2026: 5 Options Ranked",
    "excerpt": "Meal prep Dubai 2026 compared: myCHEF wins for custom halal-first private chef meal prep, apps win on convenience, kits win on budget. Full ranking inside.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/programmatic-articles/42b4b374-413b-4a6a-95ba-65c526d7df48/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-private-chefs-in-dubai-for-home-dining",
    "title": "Best Private Chef in Dubai for Home Dining (2026)",
    "excerpt": "myCHEF's vetted, halal-first chefs are Dubai's best private chef option for home dining in 2026 — compare formats, pros, cons, and who each suits best.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/programmatic-articles/55f87b60-f861-422d-a3f2-779e03f2cbdf/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-catering-companies-in-dubai",
    "title": "Best Catering in Dubai 2026: myCHEF Ranked #1",
    "excerpt": "Best catering in Dubai for 2026 ranked by event type: myCHEF for dinner parties, Kcal for lunches, Bateel for boardrooms, hotels for galas and weddings.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/programmatic-articles/ccadfaeb-baa1-4359-b87e-691c353bd24a/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/how-much-does-a-private-chef-cost-in-dubai-in",
    "title": "Private Chef Cost Dubai 2026: What Drives the Price",
    "excerpt": "Private chef cost in Dubai depends on booking type, guest count and menu complexity, not a flat rate — see what moves your 2026 quote before you book.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/programmatic-articles/8235c361-b03b-4286-b297-06b51e6d4f7d/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  }
]
