// Generated by scripts/ryze-convert.mjs. Do not edit by hand.
export const RYZE_BLOG_POSTS = [
  {
    "slug": "/blog/best-cocktail-party-catering-companies-in-dubai",
    "title": "Best cocktail party catering companies in Dubai 2026",
    "excerpt": "Compare six cocktail party catering models in Dubai for 2026 — chef-led myCHEF menus, hotel receptions, drop-off canapés, corporate and yacht catering.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/023d6e8e-8051-428b-8f82-41884070f5e2/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-drop-off-catering-services-in-dubai",
    "title": "Best drop-off catering services in Dubai 2026",
    "excerpt": "Compare the best drop-off catering options in Dubai for 2026 by use case: dinner parties, corporate lunches, halal buffets and big-batch celebrations.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/acebd3c7-a9cd-4f58-b84d-36333303940a/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-desert-dining-catering-companies-in-dubai",
    "title": "Best desert dining catering companies in Dubai 2026",
    "excerpt": "Compare the best desert dining catering companies in Dubai for 2026 — private chefs, grazing tables, hotel camps and production crews — by guest count and fit.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/d3bc52c2-b6df-40f4-a5bb-9426211a5340/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-private-cooking-class-experiences-in-dubai",
    "title": "Best Private Cooking Classes in Dubai: What to Compare",
    "excerpt": "Choose a cooking class by the cuisine you want to learn, how much hands-on time you expect and the setting that suits your group. A private session at home, a teaching studio and a group workshop offer different experiences.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/f554074d-e4a4-4b93-9f72-f9c6bb8e1cb0/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-bbq-catering-companies-in-dubai",
    "title": "Best BBQ Catering Companies in Dubai: What to Compare",
    "excerpt": "Choosing BBQ catering in Dubai starts with the venue and the style of gathering. A live grill, prepared BBQ menu and fully staffed outdoor meal each require a different setup. Compare the complete service around the food you want to share.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/b3cca5ed-e41d-4f99-ae19-5a408b2eeaa7/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-corporate-lunch-catering-companies-in-dubai",
    "title": "Corporate Catering Lunch Options in Dubai: What to Compare",
    "excerpt": "A good corporate lunch fits the working day. Compare providers on menu consistency, delivery windows, dietary information and the level of service your office needs, from individual meals to a staffed client lunch.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/af4c58c5-d4af-4c10-ae48-22cee761f7ff/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-grazing-table-catering-companies-in-dubai",
    "title": "Best Grazing Table Catering in Dubai: What to Compare",
    "excerpt": "A grazing table should be inviting throughout the agreed service, with the right quantities and a practical replenishment plan. Compare the food, setup and supervision as carefully as the photographs.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/ad794ce4-8480-4e04-9560-e63af1c4589b/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-ramadan-iftar-catering-companies-in-dubai",
    "title": "Best Ramadan Iftar Catering Companies Dubai: What to Compare",
    "excerpt": "Choosing iftar catering in Dubai means balancing a generous menu with precise timing. Compare the provider’s approach to readiness for Maghrib, guest service, halal sourcing and the space where everyone will gather.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/77b0b456-a0f6-429a-9c1c-4a65b7b10689/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-kids-birthday-party-caterers-in-dubai",
    "title": "Best Kids Birthday Catering Companies Dubai: What to Compare",
    "excerpt": "Children’s birthday catering works best when the food fits the ages, activities and length of the party. Compare providers on suitable portions, clear dietary communication and practical service for both children and adults.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/7308a5fa-aae3-44b8-8a4a-ba5ae1d7ca23/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-yacht-catering-services-in-dubai",
    "title": "Best Yacht Catering Companies in Dubai: What to Compare",
    "excerpt": "Yacht catering in Dubai needs to suit the vessel as well as the occasion. Compare menus, loading arrangements, chilled storage and the service team against the yacht’s facilities and the captain’s itinerary.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/69f7a76e-9eb1-49b9-968c-a477ff1e4f2a/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-vegan-catering-services-in-dubai",
    "title": "Best Vegan Catering Companies in Dubai: What to Compare",
    "excerpt": "A strong vegan menu offers variety, substance and considered presentation. Compare catering providers on the full ingredient list, the balance of the meal and their ability to serve it well in your chosen setting.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/5be85fe9-0e92-4e91-bd47-b999e91eedb8/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-corporate-event-catering-companies-in-dubai",
    "title": "Best Corporate Catering Companies Dubai: What to Compare",
    "excerpt": "Corporate event catering should support the purpose and pace of the occasion. Compare providers by their ability to coordinate menus, service and venue requirements around your programme, from a launch reception to an awards dinner.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/4f43a200-5379-4b9f-8282-6b6a4366c995/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-luxury-private-dining-experiences-in-dubai",
    "title": "Best Luxury Private Dining Experiences Dubai: What to Compare",
    "excerpt": "The right private dining experience feels suited to the people at the table. Compare the setting, menu, level of interaction with the chef and practical arrangements, whether you prefer a quiet dinner at home or a more distinctive venue.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/4755c939-e288-442c-8a1c-7a449a3229dd/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-arabic-catering-companies-in-dubai",
    "title": "Best Arabic Catering Companies Dubai: What to Compare",
    "excerpt": "Arabic catering in Dubai can range from a generous mezze table to a wedding buffet or a family meal built around traditional rice and grilled dishes. Compare the regional menu, presentation and service against the occasion you are planning.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/2d8406d3-01b7-4c0d-9c95-e19dfc834617/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-brunch-catering-services-in-dubai",
    "title": "Best Brunch Catering Companies in Dubai: What to Compare",
    "excerpt": "Brunch catering in Dubai should make a morning gathering feel relaxed and well considered. Compare the balance of sweet and savoury dishes, the preparation needed on site and the service that keeps the table comfortable.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/0f4171aa-db5b-4182-abee-6137d3756443/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-halal-catering-companies-in-dubai",
    "title": "Best Halal Catering Companies Dubai: What to Compare",
    "excerpt": "Choosing halal catering in Dubai requires clarity about ingredients, sourcing and preparation. Compare providers on the documentation they can supply and their ability to meet the specific requirements of your guests and event.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/0b41e2c7-512d-457c-bb29-985c907f0574/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-private-chefs-for-villas-in-dubai",
    "title": "Best Private Chefs for Villas in Dubai: What to Compare",
    "excerpt": "A private chef for a Dubai villa should fit the household and the occasion. Compare regular cooking plans with one-off dining, then review the chef’s style, the kitchen facilities and the support included in the arrangement.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/06cc8958-5c24-44f4-a12d-781923e653a5/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  },
  {
    "slug": "/blog/best-wedding-catering-companies-in-dubai",
    "title": "Best Wedding Catering Companies in Dubai: What to Compare",
    "excerpt": "Wedding catering in Dubai should bring the menu, venue and service together with care. Compare providers on their ability to plan the meal you want, communicate clearly and coordinate with the people responsible for the rest of your celebration.",
    "category": "Guides",
    "image": "https://gwvckixiegkllthleuyt.supabase.co/storage/v1/object/public/workspace-article-images-public/050826a0-32aa-4f57-bf3f-862e747b6c72/featured.jpg",
    "hub": "menus-dietary",
    "date": "September 2026"
  }
]
