// Generated by scripts/ryze-convert.mjs. Do not edit by hand.
export const RYZE_BLOG_PATHS: string[] = [
  "/blog/best-drop-off-catering-services-in-dubai",
  "/blog/best-desert-dining-catering-companies-in-dubai",
  "/blog/best-private-cooking-class-experiences-in-dubai",
  "/blog/best-bbq-catering-companies-in-dubai",
  "/blog/best-corporate-lunch-catering-companies-in-dubai",
  "/blog/best-grazing-table-catering-companies-in-dubai",
  "/blog/best-ramadan-iftar-catering-companies-in-dubai",
  "/blog/best-kids-birthday-party-caterers-in-dubai",
  "/blog/best-yacht-catering-services-in-dubai",
  "/blog/best-vegan-catering-services-in-dubai",
  "/blog/best-corporate-event-catering-companies-in-dubai",
  "/blog/best-luxury-private-dining-experiences-in-dubai",
  "/blog/best-arabic-catering-companies-in-dubai",
  "/blog/best-brunch-catering-services-in-dubai",
  "/blog/best-halal-catering-companies-in-dubai",
  "/blog/best-private-chefs-for-villas-in-dubai",
  "/blog/best-wedding-catering-companies-in-dubai"
]
