// Generated by scripts/ryze-convert.mjs. Do not edit by hand.
export const RYZE_BLOG_POSTS = [
  {
    "slug": "/blog/ryze-setup-test",
    "title": "Ryze Publishing Setup Test",
    "excerpt": "Temporary test article used to verify the myCHEF GitHub publishing pipeline.",
    "category": "Guides",
    "image": "https://www.mychef.ae/images/mychef-dubai-blog-hero.webp",
    "hub": "menus-dietary",
    "date": "September 2026"
  }
]
