import raw from './siloMap.json'

/**
 * Internal-linking contract, generated by scripts/generate-silo-map.py from the
 * locked keyword map. Direction is fixed:
 *
 *     hub -> children -> guides/blogs -> commercial owner
 *
 * Templates read one page and render modules from it:
 *
 *     const page = getSiloPage(pathname)
 *     page.siblings           replaces "You May Also Like"
 *     page.featuredChildren   hub cards, hubs only
 *     page.siloIndex          rest of the silo, hubs only
 *     page.commercialOwners   blog/guide CTA to the booking page
 *     page.supportingGuides   inverse: a landing page offers its guides
 *
 * Never hand-write a sibling list for a new URL. Add the URL to the keyword
 * map and regenerate — a guessed related list is how an exact-match farm
 * starts. Anything in `doNotLink` must never be rendered.
 *
 * The JSON is index-encoded to keep it out of the critical bundle (537KB
 * readable becomes 43KB); docs/seo/silo-map.json is the version to read.
 */

interface CompactPage {
  h: number
  H: number
  b: number[]
  s: number[]
  c: number[]
  i: number[]
  o: number[]
  g: number[]
  a: number[]
  z: string
}

interface CompactMap {
  u: string[]
  l: string[]
  d: number[]
  p: Record<string, CompactPage>
}

const map = raw as CompactMap

export interface SiloLink {
  url: string
  label: string
}

export interface SiloPage {
  url: string
  silo: string
  isHub: boolean
  /** One-sentence context link in the first third of the page. Not a heading. */
  uplink: SiloLink | null
  breadcrumb: SiloLink[]
  siblings: SiloLink[]
  featuredChildren: SiloLink[]
  siloIndex: SiloLink[]
  commercialOwners: SiloLink[]
  supportingGuides: SiloLink[]
  areas: SiloLink[]
}

const link = (i: number): SiloLink => ({ url: map.u[i], label: map.l[i] })
const links = (ids: number[]): SiloLink[] => ids.map(link)

export const doNotLink: ReadonlySet<string> = new Set(map.d.map((i) => map.u[i]))

/** Trailing slashes and hashes are not distinct pages. */
function normalize(pathname: string): string {
  const clean = pathname.split('?')[0].split('#')[0]
  return clean.length > 1 ? clean.replace(/\/+$/, '') : clean
}

/** Returns null for a path the keyword map has never seen (404s, previews). */
export function getSiloPage(pathname: string): SiloPage | null {
  const entry = map.p[normalize(pathname)]
  if (!entry) return null
  return {
    url: normalize(pathname),
    silo: entry.z,
    isHub: entry.H === 1,
    uplink: entry.h >= 0 ? link(entry.h) : null,
    breadcrumb: links(entry.b),
    siblings: links(entry.s),
    featuredChildren: links(entry.c),
    siloIndex: links(entry.i),
    commercialOwners: links(entry.o),
    supportingGuides: links(entry.g),
    areas: links(entry.a),
  }
}
