import { readdir, readFile, writeFile, mkdir, unlink } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const sourceDir = path.join(root, 'blog/data')
const pageDir = path.join(root, 'src/content/ryze-pages')
const pathsFile = path.join(root, 'src/content/ryzeBlogPaths.ts')
const postsFile = path.join(root, 'src/content/ryzeBlogPosts.ts')
const sitemapFile = path.join(root, 'public/sitemap.xml')
const site = 'https://www.mychef.ae'

const validSlug = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const xmlEscape = (value) => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&apos;')

function formatDate(value) {
  const date = value ? new Date(value) : new Date()
  if (Number.isNaN(date.getTime())) return 'Recent'
  return new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(date)
}

function imageFrom(article) {
  if (!article.image || typeof article.image !== 'object') return null
  if (typeof article.image.url !== 'string' || article.image.url.length === 0) return null
  return {
    url: article.image.url,
    alt: typeof article.image.alt === 'string' && article.image.alt.length > 0
      ? article.image.alt
      : article.title,
  }
}

await mkdir(sourceDir, { recursive: true })
await mkdir(pageDir, { recursive: true })

const sourceNames = (await readdir(sourceDir)).filter((name) => name.endsWith('.json')).sort()
const articles = []

for (const name of sourceNames) {
  const source = JSON.parse(await readFile(path.join(sourceDir, name), 'utf8'))
  if (source.status !== 'published') continue
  if (!validSlug.test(source.slug || '')) throw new Error('Invalid Ryze article slug in ' + name)
  if (!source.title || (!source.body_html && !source.body_markdown)) {
    throw new Error('Missing title or body in ' + name)
  }

  const article = {
    slug: source.slug,
    title: source.title,
    body_html: source.body_html || '',
    body_markdown: source.body_markdown || '',
    meta_title: source.meta_title || source.title,
    meta_description: source.meta_description || source.excerpt || '',
    excerpt: source.excerpt || source.meta_description || '',
    primary_keyword: source.primary_keyword || null,
    image: imageFrom(source),
    published_at: source.published_at || null,
    updated_at: source.updated_at || source.published_at || null,
    status: 'published',
  }

  articles.push(article)
  await writeFile(
    path.join(pageDir, article.slug + '.json'),
    JSON.stringify(article, null, 2) + '\n',
  )
}

const activePages = new Set(articles.map((article) => article.slug + '.json'))
for (const name of await readdir(pageDir)) {
  if (name.endsWith('.json') && !activePages.has(name)) await unlink(path.join(pageDir, name))
}

articles.sort((a, b) => String(b.published_at || '').localeCompare(String(a.published_at || '')))
const paths = articles.map((article) => '/blog/' + article.slug)
const posts = articles.map((article) => ({
  slug: '/blog/' + article.slug,
  title: article.title,
  excerpt: article.excerpt,
  category: 'Guides',
  image: article.image ? article.image.url : '/images/mychef-dubai-blog-hero.webp',
  hub: 'menus-dietary',
  date: formatDate(article.published_at),
}))

await writeFile(
  pathsFile,
  '// Generated by scripts/ryze-convert.mjs. Do not edit by hand.\n' +
    'export const RYZE_BLOG_PATHS: string[] = ' + JSON.stringify(paths, null, 2) + '\n',
)
await writeFile(
  postsFile,
  '// Generated by scripts/ryze-convert.mjs. Do not edit by hand.\n' +
    'export const RYZE_BLOG_POSTS = ' + JSON.stringify(posts, null, 2) + '\n',
)

let sitemap = await readFile(sitemapFile, 'utf8')
sitemap = sitemap.replace(/\n?\s*<!-- RYZE:START -->[\s\S]*?<!-- RYZE:END -->\n?/g, '\n')
const sitemapRows = articles.map((article) => {
  const updated = String(article.updated_at || article.published_at || new Date().toISOString()).slice(0, 10)
  return '  <url><loc>' + xmlEscape(site + '/blog/' + article.slug) + '</loc><lastmod>' +
    xmlEscape(updated) + '</lastmod><priority>0.7</priority><changefreq>monthly</changefreq></url>'
})
const sitemapBlock = [
  '  <!-- RYZE:START -->',
  ...sitemapRows,
  '  <!-- RYZE:END -->',
].join('\n')
sitemap = sitemap.replace('</urlset>', sitemapBlock + '\n</urlset>')
await writeFile(sitemapFile, sitemap)

console.log('Converted ' + articles.length + ' published Ryze article(s).')
