import assert from 'node:assert/strict'
import { assistantCount, bookingErrors, calculateDining, compatible, createDiningInput, diningBrief, diningSharePath, dubaiToday, earliestDiningDate, emptyDetails, generateMenu, menuSlots, readDiningPrefill, toggleDrink, validDiningDate, type DiningInput, type DiningStyle } from '../src/lib/privateDining'
import { DINING_CONFIG as config } from '../src/content/privateDiningConfig'
const base=createDiningInput()
const details={...emptyDetails,name:'Test guest',whatsapp:'+971501234567',email:'guest@example.com',date:earliestDiningDate(),kitchen:'yes' as const}
const A=calculateDining(base)
assert.equal(A.total,2562);assert.equal(A.perGuest,427);assert.equal(A.food,1200);assert.equal(A.chefFee,1200);assert.equal(A.vat,122)
const fine=generateMenu({...base,style:'fine',cuisine:'japanese',guests:12,area:'palm-jumeirah',fineEquipment:'hire',waiters:1,drinkIds:['mocktail-package']})
const B=calculateDining(fine)
assert.equal(B.food,4800);assert.equal(B.kitchenTeam,1600);assert.equal(B.uplift,3200);assert.equal(B.serviceStaff,450);assert.equal(B.fineEquipment,1440);assert.equal(B.cars,1);assert.equal(B.total,13109.25);assert.equal(B.perGuest,1092.44)
assert.equal(calculateDining({...fine,fineEquipment:'yes',drinkIds:[]}).total,10652.25)
assert.equal(calculateDining({...fine,fineEquipment:'yes'}).uplift,B.uplift)
const delivered=generateMenu({...base,service:'delivery',guests:20,cuisine:'italian',area:'abu-dhabi',drinkIds:['refreshments']})
const C=calculateDining(delivered)
assert.equal(C.total,6405);assert.equal(C.packaging,400);assert.equal(C.chefFee,0);assert.equal(C.assistants,0);assert.equal(C.cars,1);assert.equal(C.transport,400)
assert.equal(calculateDining({...base,service:'delivery'}).packaging,200)
for(const [guests,assistants] of [[6,0],[8,0],[9,1],[18,1],[19,2],[28,2],[29,3],[38,3],[39,4],[48,4],[49,5],[58,5],[59,6]]){assert.equal(assistantCount('home',guests),assistants);assert.equal(assistantCount('delivery',guests),0)}
for(const invalid of [5,6.5,NaN,Infinity,-1,1001])assert.equal(calculateDining({...base,guests:invalid}).total,null)
for(const service of ['delivery','home'] as const){assert.equal(calculateDining({...base,service,area:'sharjah'}).transport,service==='home'?350:300);assert.equal(calculateDining({...base,service,area:'abu-dhabi'}).transport,service==='home'?500:400)}
const cars=calculateDining({...base,guests:19,waiters:2,bartenders:1})
assert.equal(cars.staffCount,6);assert.equal(cars.cars,2);assert.equal(cars.transport,80)
assert.equal(calculateDining({...base,guests:51}).total,null);assert.equal(calculateDining({...base,service:'delivery',guests:100}).total!==null,true);assert.equal(calculateDining({...base,service:'delivery',guests:101}).total,null)
assert.equal(calculateDining(base,{...details,kitchen:'field'}).total,null)
assert.equal(calculateDining({...base,service:'delivery',waiters:1}).total,null)
assert.equal(calculateDining({...base,service:'delivery',style:'fine'}).total,null)
assert.equal(calculateDining({...base,drinkIds:['own-alcohol']}).total,null)
assert.equal(calculateDining({...base,drinkIds:['cocktail-kit'],waiters:1}).total,null)
assert.equal(calculateDining({...base,drinkIds:['coffee','tea','coffee-tea']}).total,null)
assert.deepEqual(toggleDrink(['water','soft','juice'],'refreshments'),['refreshments'])
assert.deepEqual(toggleDrink(['coffee'],'coffee-tea'),['coffee-tea'])
assert.deepEqual(toggleDrink(['refreshments'],'water'),['water'])
let menus=0
for(const cuisine of config.cuisines)for(const style of config.styles)for(const mood of config.moods){
 const i=generateMenu({...base,cuisine:cuisine.id,style:style.id as DiningStyle,mood:mood.id,fineEquipment:'yes',dietary:{vegetarian:2,vegan:2}})
 const q=calculateDining(i);assert.equal(q.errors.length,0,q.errors.join(', '));assert.notEqual(q.total,null)
 assert.equal(q.groups.reduce((n,g)=>n+g.count,0),6)
 assert.equal(q.food,6*config.foodPrices[i.style][cuisine.id as keyof typeof config.foodPrices.family])
 for(const g of q.groups)for(const d of g.dishes)assert.ok(d&&compatible(d,g.diet))
 const allVegan=calculateDining({...i,dietary:{vegetarian:0,vegan:6}});assert.equal(allVegan.total,q.total)
 const allStandard=calculateDining({...i,dietary:{vegetarian:0,vegan:0}});assert.equal(allStandard.total,q.total)
 menus++
}
for(let extra=0;extra<=4;extra++){
 const i=generateMenu({...base,extraDishes:extra,dietary:{vegetarian:1,vegan:1}}),q=calculateDining(i)
 assert.equal(q.errors.length,0);assert.equal(menuSlots('family',extra).length,4+extra);assert.equal(q.food,1200+extra*50*6)
}
const swap={...base,dishIds:['indian-starter-06',...base.dishIds.slice(1)]};assert.equal(calculateDining(swap).total,A.total)
assert.equal(calculateDining({...base,dietary:{vegetarian:4,vegan:3}}).total,null)
assert.equal(calculateDining({...base,dishIds:['italian-starter-01',...base.dishIds.slice(1)]}).total,null)
assert.equal(calculateDining({...base,furniture:{chair:6}}).total,Math.round((2440+180+250)*1.05*100)/100)
assert.equal(calculateDining({...base,furniture:{chair:6}}).isFrom,true)
assert.equal(calculateDining({...base,furniture:{chair:6,linen:6,unknown:1}}).total,null)
const overtime=calculateDining({...base,kitchenHours:7,waiters:1,serviceHours:6})
assert.equal(overtime.kitchenOvertime,150);assert.equal(overtime.serviceStaff,525)
assert.equal(dubaiToday(new Date('2026-10-03T21:00:00Z')),'2026-10-04')
assert.equal(earliestDiningDate('2026-12-28'),'2027-01-02');assert.equal(earliestDiningDate('2028-02-25'),'2028-03-01')
assert.equal(validDiningDate('2026-02-30','2026-02-01'),false);assert.equal(validDiningDate('2026-10-08','2026-10-04'),false);assert.equal(validDiningDate('2026-10-09','2026-10-04'),true)
assert.equal(bookingErrors(base,details).length,0)
assert.ok(bookingErrors(base,{...details,email:'bad'}).some(e=>e.includes('email')))
const brief=diningBrief(fine,details,'call');assert.ok(brief.includes('AED 13,109.25'));assert.ok(brief.includes('Please call'));assert.ok(brief.includes('Japanese'));assert.ok(brief.includes('Kitchen assistants (1)'))
const share=diningSharePath(fine,{...details,dietaryNotes:'private medical detail'})
assert.equal(share.includes(details.email),false);assert.equal(share.includes('medical'),false);assert.equal(share.includes('whatsapp='),false)
const pre=readDiningPrefill(share.split('?')[1].split('#')[0]);assert.equal(pre.input.guests,12);assert.equal(pre.input.style,'fine');assert.equal(pre.input.area,'palm-jumeirah')
assert.equal(readDiningPrefill('?guests=-2&style=fine&service=delivery').input.style,'family')
console.log(`Private dining v2: all 3 worked examples, ${menus} style/cuisine/mood combinations, dietary parity, boundaries, extras, overtime and share links passed.`)
