#!/usr/bin/env python3
"""One navigation bar across every board page, injected at publish time.

Nine pages are generated by nine builders, each with its own HTML. Rather than keep nine
copies of a nav in sync, the bar is added to the published copies in public/seo/ — so a page
added later gets it for free, and the builders stay unaware of each other.

    python3 docs/seo/keyword-map/inject-nav.py public/seo
"""
import pathlib, re, sys

OUT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "public/seo")

# order = how you actually work: what the site owns, then what to do next, then how it is doing
PAGES = [
    ("status.html", "Status", "is every source connected and feeding data"),
    ("index.html", "Board", "every URL and its locked keywords"),
    ("ownership.html", "Keywords", "one row per keyword, with its score"),
    ("report.html", "Research", "volume, difficulty, intent, position"),
    ("demand.html", "Demand", "what each page's keyword set is worth"),
    ("backlog.html", "Backlog", "phrases no page owns yet"),
    ("links.html", "Links", "internal link profile per URL"),
    ("gaps.html", "Gaps", "what competitors cover and we do not"),
    ("architecture.html", "Architecture", "the sitemap as an authority map"),
    ("ai-visibility.html", "AI answers", "who Claude names for buyer prompts"),
    ("actions.html", "Actions", "every change the agent made, newest first"),
    ("ask.html", "Ask", "put a question to the read-only SEO analyst"),
]

CSS = """
<style id="board-nav-css">
:root{--bn-bg:#10201f;--bn-ink:#e8efec;--bn-dim:#93a7a3;--bn-accent:#e0a24a;--bn-line:#243937}
.board-nav{position:sticky;top:0;z-index:50;background:var(--bn-bg);color:var(--bn-ink);
  font:500 13px/1.2 Inter,-apple-system,system-ui,sans-serif;border-bottom:1px solid var(--bn-line);
  display:flex;align-items:stretch;gap:0;overflow-x:auto;-webkit-overflow-scrolling:touch}
.board-nav::-webkit-scrollbar{height:0}
.board-nav .brand{display:flex;align-items:center;gap:8px;padding:11px 16px;white-space:nowrap;
  font-weight:700;letter-spacing:-.01em;border-right:1px solid var(--bn-line)}
.board-nav .brand i{width:7px;height:7px;border-radius:50%;background:var(--bn-accent);display:block}
.board-nav .brand span{color:var(--bn-dim);font-weight:500;font-size:11px;letter-spacing:.08em;text-transform:uppercase}
.board-nav a{display:flex;align-items:center;padding:11px 14px;color:var(--bn-dim);text-decoration:none;
  white-space:nowrap;border-bottom:2px solid transparent}
.board-nav a:hover{color:var(--bn-ink);background:rgba(255,255,255,.04)}
.board-nav a.on{color:var(--bn-ink);border-bottom-color:var(--bn-accent)}
.board-nav .spacer{flex:1}
.board-nav .stamp{display:flex;align-items:center;padding:11px 16px;color:var(--bn-dim);font-size:11px;
  white-space:nowrap;letter-spacing:.04em}
@media (max-width:700px){.board-nav .brand span{display:none}.board-nav .stamp{display:none}}
body{margin-top:0}
</style>
"""


def bar(current):
    # Absolute paths, always. The board is served at /seo (a rewrite, no trailing slash), so a
    # relative href resolves against the site root and 404s — which is what happened to every
    # link on every page until this was fixed.
    links = "".join(
        f'<a href="/seo/{f}" class="{"on" if f == current else ""}" title="{t}">{label}</a>'
        for f, label, t in PAGES if (OUT / f).exists())
    return (CSS + '<nav class="board-nav" aria-label="Board sections">'
            '<div class="brand"><i></i>myCHEF Data Board <span>agent-run</span></div>'
            + links +
            '<div class="spacer"></div><div class="stamp">password-gated · noindex</div></nav>')


KNOWN = {f for f, _, _ in PAGES} | {"report.csv", "keywords.csv"}

def absolutise(html):
    """Every in-board link becomes /seo/… so it works from /seo and /seo/index.html alike."""
    return re.sub(r'href="(?!https?:|/|#|mailto:)([\w.-]+\.(?:html|csv))(#[^"]*)?"',
                  lambda m: f'href="/seo/{m.group(1)}{m.group(2) or ""}"' if m.group(1) in KNOWN else m.group(0),
                  html)


def strip_h1_links(html):
    """The page titles each carried their own copy of the nav. The bar does that job now."""
    m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.S)
    if not m: return html
    inner = re.sub(r"\s*<a\b[^>]*>.*?</a>", "", m.group(1), flags=re.S).rstrip()
    return html[:m.start(1)] + inner + html[m.end(1):]


def main():
    if not OUT.exists():
        print(f"no {OUT} — nothing to inject"); return 0
    done = 0
    for f, _, _ in PAGES:
        p = OUT / f
        if not p.exists(): continue
        html = p.read_text(encoding="utf-8", errors="ignore")
        if 'class="board-nav"' in html: continue          # already injected by an earlier publish
        html = absolutise(html)
        html = strip_h1_links(html)
        m = re.search(r"<body[^>]*>", html)
        if not m: continue
        p.write_text(html[:m.end()] + bar(f) + html[m.end():], encoding="utf-8")
        done += 1
    print(f"navigation added to {done} board page(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
