import {
  Briefcase,
  CalendarClock,
  Clapperboard,
  ClipboardList,
  Cake,
  Flame,
  Gift,
  GlassWater,
  Handshake,
  Heart,
  Home,
  Package,
  Plane,
  PartyPopper,
  Presentation,
  Salad,
  Sandwich,
  Ship,
  Truck,
  UtensilsCrossed,
  Users,
  Baby,
  Building2,
  Sparkles,
  GraduationCap,
  HeartPulse,
  Landmark,
  Megaphone,
  CookingPot,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/** Path → icon for the four top-level clusters (used by the mobile accordion). */
export const NAV_CLUSTER_ICONS: Record<string, LucideIcon> = {
  // Catering — service formats
  '/catering-dubai': UtensilsCrossed,
  '/buffet-catering-dubai': Salad,
  '/canape-catering-dubai': Sandwich,
  '/live-cooking-stations-dubai': Flame,
  '/bbq-catering-dubai': Flame,
  '/grazing-table-dubai': GlassWater,
  '/drop-off-catering-dubai': Truck,
  // Catering — venues
  '/villas-private-residences': Home,
  '/yachts': Ship,
  '/private-jet-catering-dubai': Plane,
  // Private events
  '/birthday-catering-dubai': Cake,
  '/private-party-catering-dubai': PartyPopper,
  '/wedding-catering-dubai': Heart,
  '/baby-shower-catering-dubai': Baby,
  '/desert-dining-dubai': Flame,
  '/afternoon-tea-catering-dubai': GlassWater,
  '/events': Sparkles,
  // Corporate
  '/corporate': Briefcase,
  '/corporate-event-catering-dubai': PartyPopper,
  '/product-launch-catering-dubai': Presentation,
  '/brand-activation-catering-dubai': Megaphone,
  '/gala-dinner-catering-dubai': Sparkles,
  '/office-catering-dubai': Building2,
  '/business-lunch-catering-dubai': Handshake,
  '/conference-catering-dubai': Presentation,
  '/exhibition-catering-dubai': Building2,
  '/staff-meals-catering-dubai': Users,
  '/production-catering-dubai': Clapperboard,
  '/corporate-retainer-dubai': CalendarClock,
  '/corporate-catering-checklist-dubai': ClipboardList,
  '/institutional-catering-dubai': Landmark,
  '/nursery-catering-dubai': Baby,
  '/school-catering-dubai': GraduationCap,
  '/hospital-catering-dubai': HeartPulse,
  '/canteen-management-dubai': CookingPot,
  // Packages
  '/catering-packages-dubai': Package,
  '/birthday-catering-package-dubai': Cake,
  '/family-feast-package-dubai': Home,
  '/corporate-dinner-package-dubai': Briefcase,
  '/date-night-package-dubai': Gift,
}
