import type { VercelRequest, VercelResponse } from '@vercel/node'
import { neon } from '@neondatabase/serverless'

/**
 * First-party event collector.
 *
 * Why this exists when GA4 is already on the page: GA4 cannot be joined to the keyword
 * tables. This one writes into the same Postgres that holds seo_keywords and seo_pages, so
 * "WhatsApp clicks per owned keyword" becomes a query instead of a guess. It is also not
 * blocked by ad blockers, because it is our own domain.
 *
 * What it never collects: no cookies, no IP address, no user id, no free text, no raw
 * search queries. A session id lives in sessionStorage and dies with the tab. Country comes
 * from Vercel's edge header, which is country-level only. Landing class is computed here
 * from the contract, not by the browser.
 *
 * Abuse limits, in order of strength:
 *   1. a fixed event vocabulary — anything else is rejected
 *   2. labels from an allow-list — anything else is dropped, not stored
 *   3. 60 events per session, enforced by the (session_id, seq) primary key
 *   4. a per-instance token bucket on a daily-salted hash of the IP, never stored
 *   5. a 3 KB body cap and a strict shape check on every field
 */

// <lock-map> generated by scripts/generate-keyword-locks.py — do not hand-edit
const PATH_PRIMARY: Record<string, string | null> = {
  "/": "private chef and catering dubai",
  "/about": "private chef company dubai",
  "/afternoon-tea-catering-dubai": "afternoon tea catering dubai",
  "/allergy-safe-catering-dubai": "allergy safe catering dubai",
  "/apartment-private-dining-dubai": "private chef for apartment dubai",
  "/arabic-catering-dubai": "arabic catering dubai",
  "/asian-catering-dubai": "asian catering dubai",
  "/baby-shower-catering-dubai": "baby shower catering dubai",
  "/bar-services-dubai": "bar services dubai",
  "/bbq-catering-dubai": "bbq catering dubai",
  "/become-a-mychef": "private chef jobs dubai",
  "/best-catering-companies-dubai": "best catering companies dubai",
  "/birthday-catering-dubai": "birthday catering dubai",
  "/birthday-catering-package-dubai": "birthday catering packages dubai",
  "/blog": null,
  "/blog/best-private-chef-birthday-dinner-dubai": "private chef for birthday dinner dubai",
  "/blog/brunch-at-home-dubai": "brunch at home dubai",
  "/blog/corporate-catering-full-service-vs-drop-off": "full service vs drop off catering dubai",
  "/blog/corporate-event-catering-ideas-dubai": "corporate event catering ideas dubai",
  "/blog/desert-dinner-party-dubai": "desert dinner party dubai",
  "/blog/dinner-party-menu-ideas-dubai": "dinner party menu ideas dubai",
  "/blog/grazing-table-vs-buffet-dubai": "grazing table vs buffet dubai",
  "/blog/halal-private-dining-dubai-what-to-ask": "what to ask a halal caterer dubai",
  "/blog/how-far-ahead-book-caterer-dubai": "how far in advance to book a caterer dubai",
  "/blog/how-much-does-private-chef-cost-dubai": "how much does private chef cost dubai",
  "/blog/how-to-hire-a-private-chef-dubai": "how to hire a private chef dubai",
  "/blog/iftar-at-home-dubai": "iftar at home dubai",
  "/blog/nye-party-catering-dubai": "nye party catering dubai",
  "/blog/private-chef-date-night-dubai": "private chef date night dubai",
  "/blog/private-chef-palm-jumeirah-guide": "private dining palm jumeirah dubai",
  "/blog/private-chef-vs-restaurant-dubai": "private chef vs restaurant dubai",
  "/blog/ramadan-iftar-catering-trends-2026": "ramadan catering trends dubai 2026",
  "/blog/vegan-catering-dubai-guide": "vegan menu ideas dubai",
  "/blog/wedding-catering-cost-dubai": "wedding catering cost dubai",
  "/blog/weekly-meal-prep-vs-full-time-chef-dubai": "meal prep vs private chef dubai",
  "/blog/yacht-party-menu-ideas-dubai": "yacht party menu ideas dubai",
  "/booking-protection-insurance": "catering cancellation policy dubai",
  "/brand-activation-catering-dubai": "brand activation catering dubai",
  "/breakfast-catering-dubai": "breakfast catering dubai",
  "/brunch-catering-dubai": "brunch catering dubai",
  "/buffet-catering-dubai": "buffet catering dubai",
  "/buffet-vs-plated-dubai": "buffet vs plated dubai",
  "/business-lunch-catering-dubai": "business lunch catering dubai",
  "/canape-catering-dubai": "canape catering dubai",
  "/case-studies": "catering case studies dubai",
  "/catering-cost-calculator-dubai": "catering cost calculator dubai",
  "/catering-dubai": "catering dubai",
  "/catering-packages-dubai": "catering packages dubai",
  "/chef-training-academy": "chef training dubai",
  "/chefs-table-dubai": "chefs table dubai",
  "/chefs/ahmed-executive-chef": null,
  "/chefs/layla-middle-eastern-chef": "arabic private chef dubai",
  "/chefs/marco-italian-chef": "italian private chef dubai",
  "/chefs/matteo-pastry-chef": "private pastry chef dubai",
  "/christmas-catering-dubai": "christmas catering dubai",
  "/cocktail-party-catering-dubai": "cocktail party catering dubai",
  "/conference-catering-dubai": "conference catering dubai",
  "/contact": null,
  "/corporate": "corporate catering dubai",
  "/corporate-catering-checklist-dubai": "corporate catering checklist dubai",
  "/corporate-dinner-package-dubai": "corporate dinner package dubai",
  "/corporate-event-catering-dubai": "corporate event catering dubai",
  "/corporate-retainer-dubai": "corporate catering contract dubai",
  "/cuisines-dubai": "multi cuisine catering dubai",
  "/date-night-package-dubai": "date night package dubai",
  "/desert-dining-dubai": "desert dining dubai",
  "/dessert-table-catering-dubai": "dessert table catering dubai",
  "/diwali-catering-dubai": "diwali catering dubai",
  "/drop-off-catering-dubai": "drop off catering dubai",
  "/dubai-catering-prices-guide": "catering prices dubai",
  "/dubai-event-catering-price-guide-2026": "event catering price guide dubai 2026",
  "/dubai-food-trends-report-2026": "dubai food trends 2026",
  "/eid-catering-dubai": "eid catering dubai",
  "/engagement-catering-dubai": "engagement party catering dubai",
  "/events": "event catering dubai",
  "/exhibition-catering-dubai": "exhibition catering dubai",
  "/family-feast-package-dubai": "family catering dubai",
  "/faq": "catering faq dubai",
  "/festive-catering-dubai": "festive catering dubai",
  "/fitness-meal-prep-dubai": "fitness meal prep dubai",
  "/founding-customer-offer": "mychef founding customer offer",
  "/full-time-private-chef-dubai": "full time private chef dubai",
  "/gala-dinner-catering-dubai": "gala dinner catering dubai",
  "/gallery": null,
  "/gift-cards": null,
  "/grazing-table-dubai": "grazing table dubai",
  "/guide/private-dining-dubai": "private dining dubai",
  "/guides": "catering checklist dubai",
  "/halal-catering-dubai": "halal catering dubai",
  "/halal-private-dining-dubai": "halal private dining dubai",
  "/how-it-works": "how to book a private chef dubai",
  "/how-to-choose-caterer-dubai": "how to choose a caterer dubai",
  "/how-we-vet-our-chefs": "private chef background checks dubai",
  "/iftar-catering-dubai": "iftar catering dubai",
  "/indian-catering-dubai": "indian catering dubai",
  "/influencer-partnerships": "food influencer partnerships dubai",
  "/italian-catering-dubai": "italian catering dubai",
  "/jain-catering-dubai": "jain catering dubai",
  "/kids-nutrition-chef-dubai": "kids meal prep dubai",
  "/live-cooking-stations-dubai": "live cooking stations dubai",
  "/locations": "catering near me dubai",
  "/locations/al-barsha": "private chef al barsha",
  "/locations/arabian-ranches": "private chef arabian ranches",
  "/locations/bluewaters-island": "private chef bluewaters island",
  "/locations/business-bay": "private chef business bay",
  "/locations/difc": "private chef difc",
  "/locations/downtown-dubai": "private chef downtown dubai",
  "/locations/dubai-hills": "private chef dubai hills",
  "/locations/dubai-marina": "private chef dubai marina",
  "/locations/emirates-hills": "private chef emirates hills",
  "/locations/jbr": "private chef jbr",
  "/locations/jlt": "private chef jlt",
  "/locations/jumeirah": "private chef jumeirah",
  "/locations/jvc": "private chef jvc",
  "/locations/palm-jumeirah": "private chef palm jumeirah",
  "/locations/umm-suqeim": "private chef umm suqeim",
  "/loyalty-programme": "mychef loyalty programme",
  "/luxury-dining-experiences": "private dining experience dubai",
  "/luxury-dinner-planning-guide-dubai": "how to plan a luxury dinner dubai",
  "/mediterranean-catering-dubai": "mediterranean catering dubai",
  "/menus": "catering menus dubai",
  "/mychef-certified": "mychef certified chefs",
  "/mychef-membership": "mychef membership",
  "/mystery-dining-dubai": "surprise dinner experience dubai",
  "/new-year-catering-dubai": "new year catering dubai",
  "/office-catering-dubai": "office catering dubai",
  "/our-chefs": "private chefs dubai",
  "/part-time-private-chef-dubai": "part time private chef dubai",
  "/partner-with-us": "catering partnerships dubai",
  "/partners": null,
  "/partners/concierge-services-dubai": "concierge services partnership dubai",
  "/partners/event-planners-dubai": "event planners partnership dubai",
  "/partners/villa-rentals-dubai": "villa rentals partnership dubai",
  "/partners/yacht-charters-dubai": "yacht charters partnership dubai",
  "/postpartum-meal-prep-dubai": "postpartum meal prep dubai",
  "/press": null,
  "/privacy-policy": null,
  "/private-chef-dubai": "private chef dubai",
  "/private-chef-dubai/how-it-works": "managed private chef service dubai",
  "/private-chef-dubai/how-your-plan-works": null,
  "/private-chef-dubai/our-chefs": null,
  "/private-chef-dubai/privacy-security": null,
  "/private-chef-dubai/quality-training": null,
  "/private-chef-prices-dubai": "private chef dubai price",
  "/private-chef-vs-catering-dubai": "private chef vs catering dubai",
  "/private-cooking-classes-dubai": "private cooking classes dubai",
  "/private-jet-catering-dubai": "private jet catering dubai",
  "/private-party-catering-dubai": "private party catering dubai",
  "/product-launch-catering-dubai": "product launch catering dubai",
  "/production-catering-dubai": "production catering dubai",
  "/proposal-dinner-dubai": "proposal dinner dubai",
  "/quality-guarantee-dubai": "catering quality guarantee dubai",
  "/ramadan-catering-dubai": "ramadan catering dubai",
  "/ramadan-catering-guide-dubai": "ramadan catering guide dubai",
  "/referral-programme": "mychef referral programme",
  "/review": null,
  "/romantic-dinner-dubai": "romantic dinner dubai",
  "/site-map": null,
  "/staff-meals-catering-dubai": "staff meals catering dubai",
  "/sushi-catering-dubai": "sushi catering dubai",
  "/tasting-menu-dubai": "private tasting menu dubai",
  "/terms": null,
  "/tourist-villa-chef-dubai": "holiday villa chef dubai",
  "/trust-and-programs": null,
  "/uae-national-day-catering-dubai": "uae national day catering dubai",
  "/vegan-catering-dubai": "vegan catering dubai",
  "/vegetarian-catering-dubai": "vegetarian catering dubai",
  "/venue-partners": "preferred caterer dubai",
  "/villa-catering-ideas-dubai": "villa catering ideas dubai",
  "/villas-private-residences": "villa chef dubai",
  "/vip-club": "mychef vip club",
  "/wedding-catering-checklist-dubai": "wedding catering checklist dubai",
  "/wedding-catering-dubai": "wedding catering dubai",
  "/wedding-catering-menu-planning-dubai": "wedding menu planning dubai",
  "/weekly-meal-prep-dubai": "meal prep dubai",
  "/wellness-meal-prep-dubai": "healthy meal prep dubai",
  "/yacht-catering-checklist-dubai": "yacht catering checklist dubai",
  "/yacht-catering-guide-dubai": "yacht catering guide dubai",
  "/yachts": "yacht catering dubai",
}
// </lock-map>

const EVENTS = new Set([
  'page_view',
  'engaged',
  'scroll_depth',
  'whatsapp_click',
  'form_submit',
  'exit',
  'cta_click',
  'inquiry_start',
  'inquiry_complete',
  'calc_use',
  'expose',
  'phone_click',
  'email_click',
])
const LABELS = new Set([
  'hero',
  'sticky',
  'price_table',
  'faq',
  'footer',
  'nav',
  'inquiry_form',
  'contact_form',
  'lead_magnet',
  'lead_form',
  'link',
])
const CHANNELS = new Set(['organic', 'paid', 'social', 'direct', 'referral', 'llm'])
const MAX_SEQ = 60
const MAX_BODY = 3072
const BUCKET_LIMIT = 60
const SESSION_RE = /^[a-z0-9]{12,32}$/
const PATH_RE = /^\/[\w\-/.]{0,180}$/

type Bucket = { n: number; minute: number }
const buckets = new Map<string, Bucket>()

function allow(key: string): boolean {
  const minute = Math.floor(Date.now() / 60000)
  const b = buckets.get(key)
  if (!b || b.minute !== minute) {
    if (buckets.size > 5000) buckets.clear()
    buckets.set(key, { n: 1, minute })
    return true
  }
  b.n += 1
  return b.n <= BUCKET_LIMIT
}

function hashed(value: string): string {
  let h = 0x811c9dc5
  for (let i = 0; i < value.length; i += 1) {
    h ^= value.charCodeAt(i)
    h = Math.imul(h, 0x01000193)
  }
  return (h >>> 0).toString(36)
}

function device(ua: string): string {
  if (/iPad|Tablet/i.test(ua)) return 'tablet'
  if (/Mobile|iPhone|Android/i.test(ua)) return 'mobile'
  if (!ua) return 'unknown'
  return 'desktop'
}

function cleanPath(url: string): string {
  const key = url.length > 1 ? url.replace(/\/+$/, '') : url
  return key || '/'
}

function landingClass(path: string): string {
  // A missing or broken lock map must cost us a column, never the endpoint. This function
  // returning "unknown" is a data gap; an exception here is a 500 on every page view.
  try {
    const key = cleanPath(path)
    if (key === '/') return 'brand'
    if (!PATH_PRIMARY || !(key in PATH_PRIMARY)) return 'unowned'
    const primary = PATH_PRIMARY[key]
    if (!primary) return 'utility'
    if (/mychef/i.test(primary)) return 'brand'
    return 'owned'
  } catch {
    return 'unknown'
  }
}

function channelClass(referrer: string | null, utmSource: string | null, utmMedium: string | null): string {
  const medium = (utmMedium || '').toLowerCase()
  const source = (utmSource || '').toLowerCase()
  if (/cpc|ppc|paid|ads|paidsearch|display/.test(medium) || /cpc|ppc|paid/.test(source)) return 'paid'
  const host = (referrer || '').toLowerCase()
  if (/chatgpt|openai|perplexity|claude\.ai|gemini\.google|copilot\.microsoft|you\.com|phind|poe\.com/.test(host)) {
    return 'llm'
  }
  if (/facebook|instagram|linkedin|t\.co$|twitter|x\.com|tiktok|pinterest|whatsapp/.test(host)) return 'social'
  if (/google\.|bing\.|yahoo\.|duckduckgo|baidu/.test(host)) return 'organic'
  if (host) return 'referral'
  return 'direct'
}

const str = (v: unknown, max: number): string | null =>
  typeof v === 'string' && v.length > 0 && v.length <= max ? v : null

const int = (v: unknown, max: number): number | null =>
  typeof v === 'number' && Number.isFinite(v) && v >= 0 && v <= max ? Math.round(v) : null

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Cache-Control', 'no-store')

  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST')
    return res.status(405).json({ error: 'Method not allowed' })
  }
  if (process.env.TRACKING_OFF === '1') return res.status(204).end()

  const dsn = process.env.DATABASE_URL
  if (!dsn) return res.status(204).end()

  const raw = typeof req.body === 'string' ? req.body : JSON.stringify(req.body ?? {})
  if (raw.length > MAX_BODY) return res.status(413).json({ error: 'Payload too large' })

  let body: Record<string, unknown>
  try {
    body = typeof req.body === 'object' && req.body !== null ? (req.body as Record<string, unknown>) : JSON.parse(raw)
  } catch {
    return res.status(400).json({ error: 'Body must be JSON' })
  }

  const session = str(body.s, 32)
  const event = str(body.e, 24)
  const url = str(body.u, 200)
  const seq = int(body.q, MAX_SEQ)

  if (!session || !SESSION_RE.test(session)) return res.status(400).json({ error: 'Bad session' })
  if (!event || !EVENTS.has(event)) return res.status(400).json({ error: 'Unknown event' })
  if (!url || !PATH_RE.test(url) || url.startsWith('/seo')) return res.status(400).json({ error: 'Bad url' })
  if (seq === null) return res.status(400).json({ error: 'Bad sequence' })

  const ip = String(req.headers['x-forwarded-for'] || '').split(',')[0].trim()
  const day = new Date().toISOString().slice(0, 10)
  if (!allow(hashed(ip + day))) return res.status(429).json({ error: 'Too many events' })

  const value = int(body.v, 86400)
  const rawLabel = str(body.l, 60)
  const label = rawLabel && LABELS.has(rawLabel) ? rawLabel : null
  const country = String(req.headers['x-vercel-ip-country'] || '').slice(0, 2).toUpperCase() || null
  const ua = String(req.headers['user-agent'] || '')
  const referrer = str(body.r, 120)
  const utmSource = str(body.us, 60)
  const utmMedium = str(body.um, 60)
  const utmCampaign = str(body.uc, 60)
  const xid = str(body.xid, 16)
  const xvRaw = str(body.xv, 1)
  const xv = xvRaw && /^[ABC]$/.test(xvRaw) ? xvRaw : null
  const ch = channelClass(referrer, utmSource, utmMedium)
  const lc = landingClass(url)
  if (!CHANNELS.has(ch)) return res.status(204).end()

  try {
    const sql = neon(dsn)
    if (seq === 0) {
      try {
        await sql`
          INSERT INTO web_sessions (session_id, started_at, landing_url, referrer_host, country, device,
                                    utm_source, utm_medium, utm_campaign, channel_class, landing_class,
                                    experiment_id, variant)
          VALUES (${session}, now(), ${url}, ${referrer}, ${country}, ${device(ua)},
                  ${utmSource}, ${utmMedium}, ${utmCampaign}, ${ch}, ${lc}, ${xid}, ${xv})
          ON CONFLICT (session_id) DO NOTHING`
      } catch {
        await sql`
          INSERT INTO web_sessions (session_id, started_at, landing_url, referrer_host, country, device,
                                    utm_source, utm_medium, utm_campaign)
          VALUES (${session}, now(), ${url}, ${referrer}, ${country}, ${device(ua)},
                  ${utmSource}, ${utmMedium}, ${utmCampaign})
          ON CONFLICT (session_id) DO NOTHING`
      }
    }
    await sql`
      INSERT INTO web_events (session_id, seq, at, event, url, value, label)
      VALUES (${session}, ${seq}, now(), ${event}, ${url}, ${value}, ${label})
      ON CONFLICT (session_id, seq) DO NOTHING`
  } catch {
    return res.status(204).end()
  }
  return res.status(204).end()
}
