// AUTO-GENERATED from docs/seo/myCHEF-AE-SEO-STANDARD.json by scripts/generate-keyword-locks.py
// Compact lock map for api/e.ts landing class. Do not hand-edit.
export const PATH_PRIMARY: Record<string, string | null> = {
  "/": "private chef and catering dubai",
  "/about": "private chef company dubai",
  "/afternoon-tea-catering-dubai": "afternoon tea catering dubai",
  "/allergy-safe-catering-dubai": "allergy safe catering dubai",
  "/apartment-private-dining-dubai": "private chef for apartment dubai",
  "/arabic-catering-dubai": "arabic catering dubai",
  "/asian-catering-dubai": "asian catering dubai",
  "/baby-shower-catering-dubai": "baby shower catering dubai",
  "/bar-services-dubai": "bar services dubai",
  "/bbq-catering-dubai": "bbq catering dubai",
  "/become-a-mychef": "private chef jobs dubai",
  "/best-catering-companies-dubai": "best catering companies dubai",
  "/birthday-catering-dubai": "birthday catering dubai",
  "/birthday-catering-package-dubai": "birthday catering packages dubai",
  "/blog": null,
  "/blog/best-private-chef-birthday-dinner-dubai": "private chef for birthday dinner dubai",
  "/blog/brunch-at-home-dubai": "brunch at home dubai",
  "/blog/corporate-catering-full-service-vs-drop-off": "full service vs drop off catering dubai",
  "/blog/corporate-event-catering-ideas-dubai": "corporate event catering ideas dubai",
  "/blog/desert-dinner-party-dubai": "desert dinner party dubai",
  "/blog/dinner-party-menu-ideas-dubai": "dinner party menu ideas dubai",
  "/blog/grazing-table-vs-buffet-dubai": "grazing table vs buffet dubai",
  "/blog/halal-private-dining-dubai-what-to-ask": "what to ask a halal caterer dubai",
  "/blog/how-far-ahead-book-caterer-dubai": "how far in advance to book a caterer dubai",
  "/blog/how-much-does-private-chef-cost-dubai": "how much does private chef cost dubai",
  "/blog/how-to-hire-a-private-chef-dubai": "how to hire a private chef dubai",
  "/blog/iftar-at-home-dubai": "iftar at home dubai",
  "/blog/nye-party-catering-dubai": "nye party catering dubai",
  "/blog/private-chef-date-night-dubai": "private chef date night dubai",
  "/blog/private-chef-palm-jumeirah-guide": "private dining palm jumeirah dubai",
  "/blog/private-chef-vs-restaurant-dubai": "private chef vs restaurant dubai",
  "/blog/ramadan-iftar-catering-trends-2026": "ramadan catering trends dubai 2026",
  "/blog/vegan-catering-dubai-guide": "vegan menu ideas dubai",
  "/blog/wedding-catering-cost-dubai": "wedding catering cost dubai",
  "/blog/weekly-meal-prep-vs-full-time-chef-dubai": "meal prep vs private chef dubai",
  "/blog/yacht-party-menu-ideas-dubai": "yacht party menu ideas dubai",
  "/booking-protection-insurance": "catering cancellation policy dubai",
  "/brand-activation-catering-dubai": "brand activation catering dubai",
  "/breakfast-catering-dubai": "breakfast catering dubai",
  "/brunch-catering-dubai": "brunch catering dubai",
  "/buffet-catering-dubai": "buffet catering dubai",
  "/buffet-vs-plated-dubai": "buffet vs plated dubai",
  "/business-lunch-catering-dubai": "business lunch catering dubai",
  "/canape-catering-dubai": "canape catering dubai",
  "/case-studies": "catering case studies dubai",
  "/catering-cost-calculator-dubai": "catering cost calculator dubai",
  "/catering-dubai": "catering dubai",
  "/catering-packages-dubai": "catering packages dubai",
  "/chef-training-academy": "chef training dubai",
  "/chefs-table-dubai": "chefs table dubai",
  "/chefs/ahmed-executive-chef": null,
  "/chefs/layla-middle-eastern-chef": "arabic private chef dubai",
  "/chefs/marco-italian-chef": "italian private chef dubai",
  "/chefs/matteo-pastry-chef": "private pastry chef dubai",
  "/christmas-catering-dubai": "christmas catering dubai",
  "/cocktail-party-catering-dubai": "cocktail party catering dubai",
  "/conference-catering-dubai": "conference catering dubai",
  "/contact": null,
  "/corporate": "corporate catering dubai",
  "/corporate-catering-checklist-dubai": "corporate catering checklist dubai",
  "/corporate-dinner-package-dubai": "corporate dinner package dubai",
  "/corporate-event-catering-dubai": "corporate event catering dubai",
  "/corporate-retainer-dubai": "corporate catering contract dubai",
  "/cuisines-dubai": "multi cuisine catering dubai",
  "/date-night-package-dubai": "date night package dubai",
  "/desert-dining-dubai": "desert dining dubai",
  "/dessert-table-catering-dubai": "dessert table catering dubai",
  "/diwali-catering-dubai": "diwali catering dubai",
  "/drop-off-catering-dubai": "drop off catering dubai",
  "/dubai-catering-prices-guide": "catering prices dubai",
  "/dubai-event-catering-price-guide-2026": "event catering price guide dubai 2026",
  "/dubai-food-trends-report-2026": "dubai food trends 2026",
  "/eid-catering-dubai": "eid catering dubai",
  "/events": "event catering dubai",
  "/exhibition-catering-dubai": "exhibition catering dubai",
  "/family-feast-package-dubai": "family catering dubai",
  "/faq": "catering faq dubai",
  "/festive-catering-dubai": "festive catering dubai",
  "/fitness-meal-prep-dubai": "fitness meal prep dubai",
  "/founding-customer-offer": "mychef founding customer offer",
  "/full-time-private-chef-dubai": "full time private chef dubai",
  "/gala-dinner-catering-dubai": "gala dinner catering dubai",
  "/gallery": null,
  "/gift-cards": "mychef gift cards",
  "/grazing-table-dubai": "grazing table dubai",
  "/guide/private-dining-dubai": "private dining dubai",
  "/guides": "catering checklist dubai",
  "/halal-catering-dubai": "halal catering dubai",
  "/halal-private-dining-dubai": "halal private dining dubai",
  "/how-it-works": "how to book a private chef dubai",
  "/how-to-choose-caterer-dubai": "how to choose a caterer dubai",
  "/how-we-vet-our-chefs": "private chef background checks dubai",
  "/iftar-catering-dubai": "iftar catering dubai",
  "/indian-catering-dubai": "indian catering dubai",
  "/influencer-partnerships": "food influencer partnerships dubai",
  "/italian-catering-dubai": "italian catering dubai",
  "/jain-catering-dubai": "jain catering dubai",
  "/kids-nutrition-chef-dubai": "kids meal prep dubai",
  "/live-cooking-stations-dubai": "live cooking stations dubai",
  "/locations": "catering near me dubai",
  "/locations/al-barsha": "private chef al barsha",
  "/locations/arabian-ranches": "private chef arabian ranches",
  "/locations/bluewaters-island": "private chef bluewaters island",
  "/locations/business-bay": "private chef business bay",
  "/locations/difc": "private chef difc",
  "/locations/downtown-dubai": "private chef downtown dubai",
  "/locations/dubai-hills": "private chef dubai hills",
  "/locations/dubai-marina": "private chef dubai marina",
  "/locations/emirates-hills": "private chef emirates hills",
  "/locations/jbr": "private chef jbr",
  "/locations/jlt": "private chef jlt",
  "/locations/jumeirah": "private chef jumeirah",
  "/locations/jvc": "private chef jvc",
  "/locations/palm-jumeirah": "private chef palm jumeirah",
  "/locations/umm-suqeim": "private chef umm suqeim",
  "/loyalty-programme": "mychef loyalty programme",
  "/luxury-dining-experiences": "luxury dining in dubai",
  "/luxury-dinner-planning-guide-dubai": "how to plan a luxury dinner dubai",
  "/mediterranean-catering-dubai": "mediterranean catering dubai",
  "/menus": "catering menus dubai",
  "/mychef-certified": "mychef certified chefs",
  "/mychef-membership": "mychef membership",
  "/mystery-dining-dubai": "surprise dinner experience dubai",
  "/new-year-catering-dubai": "new year catering dubai",
  "/office-catering-dubai": "office catering dubai",
  "/our-chefs": "private chefs dubai",
  "/part-time-private-chef-dubai": "part time private chef dubai",
  "/partner-with-us": "catering partnerships dubai",
  "/partners": null,
  "/partners/concierge-services-dubai": "concierge services partnership dubai",
  "/partners/event-planners-dubai": "event planners partnership dubai",
  "/partners/villa-rentals-dubai": "villa rentals partnership dubai",
  "/partners/yacht-charters-dubai": "yacht charters partnership dubai",
  "/postpartum-meal-prep-dubai": "postpartum meal prep dubai",
  "/press": null,
  "/privacy-policy": null,
  "/private-chef-dubai": "private chef dubai",
  "/private-chef-dubai/how-it-works": "managed private chef service dubai",
  "/private-chef-dubai/how-your-plan-works": null,
  "/private-chef-dubai/our-chefs": null,
  "/private-chef-dubai/privacy-security": null,
  "/private-chef-dubai/quality-training": null,
  "/private-chef-prices-dubai": "private chef dubai price",
  "/private-chef-vs-catering-dubai": "private chef vs catering dubai",
  "/private-cooking-classes-dubai": "private cooking classes dubai",
  "/private-jet-catering-dubai": "private jet catering dubai",
  "/private-party-catering-dubai": "private party catering dubai",
  "/product-launch-catering-dubai": "product launch catering dubai",
  "/production-catering-dubai": "production catering dubai",
  "/proposal-dinner-dubai": "proposal dinner dubai",
  "/quality-guarantee-dubai": "catering quality guarantee dubai",
  "/ramadan-catering-dubai": "ramadan catering dubai",
  "/ramadan-catering-guide-dubai": "ramadan catering guide dubai",
  "/referral-programme": "mychef referral programme",
  "/review": null,
  "/romantic-dinner-dubai": "romantic dinner dubai",
  "/site-map": null,
  "/staff-meals-catering-dubai": "staff meals catering dubai",
  "/sushi-catering-dubai": "sushi catering dubai",
  "/tasting-menu-dubai": "private chef tasting menu dubai",
  "/terms": null,
  "/tourist-villa-chef-dubai": "holiday villa chef dubai",
  "/trust-and-programs": null,
  "/uae-national-day-catering-dubai": "uae national day catering dubai",
  "/vegan-catering-dubai": "vegan catering dubai",
  "/vegetarian-catering-dubai": "vegetarian catering dubai",
  "/venue-partners": "preferred caterer dubai",
  "/villa-catering-ideas-dubai": "villa catering ideas dubai",
  "/villas-private-residences": "villa chef dubai",
  "/vip-club": "mychef vip club",
  "/wedding-catering-checklist-dubai": "wedding catering checklist dubai",
  "/wedding-catering-dubai": "wedding catering dubai",
  "/wedding-catering-menu-planning-dubai": "wedding menu planning dubai",
  "/weekly-meal-prep-dubai": "meal prep dubai",
  "/wellness-meal-prep-dubai": "healthy meal prep dubai",
  "/yacht-catering-checklist-dubai": "yacht catering checklist dubai",
  "/yacht-catering-guide-dubai": "yacht catering guide dubai",
  "/yachts": "yacht catering dubai",
}
